# -------- Stage 1: Extract layers --------
FROM eclipse-temurin:21-jre-jammy AS builder

WORKDIR extracted
ADD ./build/libs/*.jar app.jar

RUN java -Djarmode=layertools -jar app.jar extract

# -------- Stage 2: Run app --------
FROM eclipse-temurin:21-jre-jammy

WORKDIR application

COPY --from=builder extracted/dependencies/ ./
COPY --from=builder extracted/spring-boot-loader/ ./
COPY --from=builder extracted/snapshot-dependencies/ ./
COPY --from=builder extracted/application/ ./

EXPOSE 8081

ENTRYPOINT ["java", "org.springframework.boot.loader.launch.JarLauncher"]